# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4926fc7a7107b5126b26eaab1f8f97be"
name = "bin-app"
handle = "bin-app-1"
application_url = "https://uncertainty-updates-hash-joining.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-cdf324ad.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,unauthenticated_read_product_listings,write_products"

[auth]
redirect_urls = [
  "https://uncertainty-updates-hash-joining.trycloudflare.com/auth/callback",
  "https://uncertainty-updates-hash-joining.trycloudflare.com/auth/shopify/callback",
  "https://uncertainty-updates-hash-joining.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
